# Titanic configuration file

# Prevent boats from sinking into the water
# See https://bugs.mojang.com/browse/MC-91206
unsinkableboats:
  # Prevents unoccupied boats from sinking when drifting into higher water.
  # This is a simpler check (default: true)
  unoccupied: true
  # Prevents occupied (driven) boats from sinking when drifting into higher water.
  # This is a more complicated check that uses ProtocolLib (default: true)
  occupied: true
