# ToughBoats configuration file

# Protect boats from collision damage (default: true)
protectboats: true

# Synchronize players' client side boat positions with server (default: true)
resync: true

# Sync interval. Only has an effect if "resync" is true. Value is in seconds.
# Players in boats will be resynchronized to their server location on this interval.
# Recommended this not be less than 60 seconds (default: 60)
sync-interval: 60