name: ToughBoats
author: Cyclometh
main: com.cyclometh.bukkit.plugins.toughboats.ToughBoats
version: 1.4
description: Fixes boats in various ways; prevents their breaking, resyncs client and
  server positions regularly

commands:
   toughboats:
      description: Management commands for ToughBoats
      usage: /<command> reload
      permission: toughboats.reload